@startuml design
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.0.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons/firebase.puml
!includeurl https://gist.githubusercontent.com/anoff/c531251183cf9590b0f86ac85d5bc353/raw/fancy.plantuml
skinparam defaultTextAlignment center

node app

DEV_FIREBASE(db, database, database)
DEV_FIREBASE(auth, auth provider, component)

app ->> db
app -down->> auth
@enduml