@startuml firestore_schema
!includeurl https://gist.githubusercontent.com/anoff/d8f48105ac4d3c7b14ca8c34d6d54938/raw/7381f13a14e048bbd3cb4ecc70369e913908151a

object users
users : Collection<user>
object radars
radars : Collection<radar>
object roles
roles : Collection<role>

users .[hidden]right roles
roles .[hidden]right radars

object user
user : _id : Firebase UID
user : uid : String
user : displayName : String
user : lastLogin : String
user : name : String
user : email : String
user : radar : radar._id

users o-- user

object role
role : _id : user._id
role : admin : Boolean (optional)
role : editor : Boolean (optional)
role : viewer : Boolean (optional)

roles o-- role
role o.. user

object radar
radar : _id : Firebase UID
radar : blips : Collection<blip>
radar : categories : Array<String>
radar : levels : Array<String>
radar : owner : user._id
radar : readers : Array<user._id>
radar : isPublic : Boolean

radars o-- radar
radar o..o user

object blip
blip : _id : Firebase UID
blip : title : String
blip : description : String
blip : category : Number
blip : level : Number
blip : link : String
blip : changes : Array<change>

radar o-- blip

object change
change : id : UUIDv4
change : date : String (ISO8601)
change : newLevel : String
change : text : String

blip o-- change

object team
team : _id : Firebase UID
team : name : String
team : members : Array<user._id>
team : tech : radar._id

user ..o team
radar ..o team

object radarAliases
radarAliases : Collection<radarAlias>

radars .[hidden]right radarAliases

object radarAlias
radarAlias : _id : user._id
radarAlias : alias : string
radarAlias : radarId : radar._id

radarAliases o-- radarAlias
radarAlias o.. radar

@enduml