@startuml firestore_schema

object users
users : Array<user>

object "user" as user
user : _id : Firebase UID
user : uid : String
user : displayName : String
user : lastLogin : String
user : name : String

users o-- user


object roles
roles : Array<role>

object "role" as role
role : _id : Firebase UID
role : admin : Boolean (optional)
role : editor : Boolean (optional)

roles o-- role
role .left. user


object blips
blips : Array<blip>

object blip
blip : _id : Auto ID
blip : title : String
blip : category : String
blip : state : String
blip : link : String
blip : changes : change

blips o-- blip

object change
change : _id : Auto ID
change : date : String
change : newState : String
change : text : String
change : author : Firebase UID

blip o-- change

@enduml