name: 'Cross-OS Test'
on:
  schedule:
    - cron:  '0 2 * * *' # UTC time

defaults:
  run:
    shell: bash

jobs:
  test-e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-20.04]
    env:
      VUE_APP_BACKEND_TYPE: 'testVolatile'
      CYPRESS_RETRIES: 3
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" >> .npmrc
      name: add auth token for npm packages
    - run: npm ci
    - run: npm run build
    - name: End-To-End tests on ${{ matrix.os }} w/ local backend
      timeout-minutes: 20
      run: npm run test:e2e:run
      continue-on-error: true # macOS keeps failing randomly, make sure other OS are tested
