name: 'Cross-Browser Test'
on:
  schedule:
    - cron:  '0 2 * * *' # UTC time

defaults:
  run:
    shell: bash

jobs:
  test-e2e:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        browser: [chrome, firefox, electron]
    container: # run in container to have specific versions of browsers available
      image: cypress/browsers:node16.5.0-chrome94-ff93 # full list at https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
      options: --ipc=host --user 1001 # see [firefox restriction](https://github.com/cypress-io/github-action#firefox)
      env:
        VUE_APP_BACKEND_TYPE: 'testVolatile'
        CYPRESS_RETRIES: 3
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" >> .npmrc
      name: add auth token for npm packages
    - run: npm ci
    - run: npm run build
    - name: End-To-End tests on ${{ matrix.browser }} w/ local backend
      timeout-minutes: 20
      run: npm run test:e2e:run:${{ matrix.browser }}
